run:
  build-tags:
    - integration
  skip-dirs:
    - api/client

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - structcheck
    - unused
    - varcheck

linters-settings:
  gocyclo:
    # Min code complexity to report, 30 by default (recommended 10-20)
    min-complexity: 25
  lll:
    line-length: 120
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable SA1019: "github.com/newrelic/go-agent" is deprecated: This package has been supplanted by version 3
