EncryptionKey: "encryption-key"
OauthClientId: "[OAUTH_CLIENT_ID]"

Applications:
  - Name: Feast
    Description: Platform for managing and serving ML features
    Configuration:
      Icon: appSearchApp
      Href: /feast
  - Name: Merlin
    Description: Platform for deploying machine learning models
    Configuration:
      Icon: machineLearningApp
      Href: /merlin
  - Name: Turing
    Description: Platform for setting up ML experiments
    Configuration:
      Icon: graphApp
      Href: /turing

Database:
  Host: "localhost"
  Database: "mlp"
  User: "mlp"
  Password: "mlp"

Docs:
  - label: "Merlin User Guide"
    href: "https://github.com/gojek/merlin/blob/main/docs/getting-started/README.md"
  - label: "Turing User Guide"
    href: "https://github.com/gojek/turing"
  - label: "Feast User Guide"
    href: "https://docs.feast.dev/user-guide/overview"

Mlflow:
  TrackingURL: "http://mlflow.mlp.dev"

Streams:
  marketing:
    - growth
    - retention
  operations:
    - inventory
    - partners
