oauthClientId: "[OAUTH_CLIENT_ID]"

applications:
  - name: Merlin
    description: Platform for deploying machine learning models
    homepage: /merlin
    configuration:
      api: /api/merlin
      iconName: machineLearningApp
      navigation:
        - label: Models
          destination: /models
        - label: Transformer Simulator
          destination: /transformer-simulator
  - name: Turing
    description: Platform for setting up ML experiments
    homepage: /turing
    configuration:
      api: /api/turing
      iconName: graphApp
      navigation:
        - label: Routers
          destination: /routers
        - label: Ensemblers
          destination: /ensemblers
        - label: Ensembling Jobs
          destination: /jobs
        - label: Experiments
          destination: /experiments
  - name: Feast
    description: Platform for managing and serving ML features
    homepage: /feast
    configuration:
      api: /feast/api
      iconName: appSearchApp
      navigation:
        - label: Entities
          destination: /entities
        - label: Feature Tables
          destination: /featuretables
        - label: Batch Ingestion Jobs
          destination: /jobs/batch
        - label: Stream Ingestion Jobs
          destination: /jobs/stream
  - name: Pipelines
    description: Platform for managing ML pipelines
    homepage: /pipeline
    configuration:
      iconName: pipelineApp
  - name: CaraML AI
    description: Gateway for accessing LLM models
    homepage: /caraml-ai
    configuration:
      iconName: timelionApp


database:
  host: "localhost"
  database: "mlp"
  user: "mlp"
  password: "mlp"

docs:
  - label: "Merlin User Guide"
    href: "https://github.com/caraml-dev/merlin/blob/main/docs/getting-started/README.md"
  - label: "Turing User Guide"
    href: "https://github.com/caraml-dev/turing"
  - label: "Feast User Guide"
    href: "https://docs.feast.dev/user-guide/overview"

mlflow:
  trackingURL: "http://mlflow.mlp.dev"

streams:
  marketing:
    - growth
    - retention
  operations:
    - inventory
    - partners

defaultSecretStorage:
  name: default-secret-storage
  type: vault
  config:
    vaultConfig:
      url: http://localhost:8200
      role: my-role
      mountPath: secret
      pathPrefix: mlp-secret/{{ .Project }}/
      # DO NOT USE THIS IN PRODUCTION
      # ONLY FOR TESTING PURPOSES
      authMethod: token
      token: root
# webhooks:
#   enabled: true
#   config:
#     OnProjectCreated:
#       - url: http://localhost:8081/project_created
#         method: POST
