version: "3"
services:
  mlp:
    depends_on:
      - postgres
      - keto
      - vault
    build: .
    image: gojecktech/mlp:dev
    ports:
      - 8080:8080
    env_file: .env.development
    environment:
      - DATABASE_HOST=postgres
    restart: on-failure

  postgres:
    image: bitnami/postgresql:14.5.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mlp
      - POSTGRESQL_PASSWORD=mlp
      - POSTGRESQL_DATABASE=mlp

  keto:
    image: oryd/keto:v0.11
    ports:
      - 4466:4466
      - 4467:4467
    command: serve -c /home/ory/keto.yaml
    volumes:
      - type: bind
        source: ./config-keto-dev.yaml
        target: /home/ory/keto.yaml

  vault:
    image: hashicorp/vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    entrypoint: vault server -dev

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.23.5
    ports:
      - 5555:8080
    volumes:
      - ./static:/app:ro
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/swagger.yaml
