version: "3"
services:
  mlp:
    depends_on:
      - postgres
      - keto
    build: .
    image: gojecktech/mlp:dev
    ports:
      - 8080:8080
    env_file: .env.development
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: bitnami/postgresql:14.5.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mlp
      - POSTGRESQL_PASSWORD=mlp
      - POSTGRESQL_DATABASE=mlp


  keto:
    depends_on:
      - keto-db
      - keto-db-migrations
    image: oryd/keto:v0.4
    ports:
      - 4466:4466
    environment:
      - DSN=postgres://keto:keto@keto-db:5432/keto?sslmode=disable
    command:
      - serve

  keto-db:
    image: bitnami/postgresql:14.5.0
    environment:
      - POSTGRESQL_USERNAME=keto
      - POSTGRESQL_PASSWORD=keto
      - POSTGRESQL_DATABASE=keto

  keto-db-migrations:
    depends_on:
      - keto-db
    image: oryd/keto:v0.4
    environment:
      - DSN=postgres://keto:keto@keto-db:5432/keto?sslmode=disable
    command:
      - migrate
      - sql
      - -e

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.23.5
    ports:
      - 5555:8080
    volumes:
      - ./static:/app:ro
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/swagger.yaml
