version: "3"
services:
  mlp:
    depends_on:
      - postgres
      - keto
    build: .
    image: gojecktech/mlp:dev
    ports:
      - 8080:8080
    env_file: .env.development
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: bitnami/postgresql:14.5.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mlp
      - POSTGRESQL_PASSWORD=mlp
      - POSTGRESQL_DATABASE=mlp

  keto:
    image: oryd/keto:v0.4
    ports:
      - 4466:4466
    environment:
      - DSN=memory
    command:
      - serve

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.23.5
    ports:
      - 5555:8080
    volumes:
      - ./static:/app:ro
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/swagger.yaml
