version: "3"
services:
  mlp:
    depends_on:
      - postgres
      - keto
    build: .
    image: gojecktech/mlp:dev
    ports:
      - 8080:8080
    env_file: .env.development
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: bitnami/postgresql:11.15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mlp
      - POSTGRESQL_PASSWORD=mlp
      - POSTGRESQL_DATABASE=mlp

  migrations:
    depends_on:
      - postgres
    image: migrate/migrate:v4.7.1
    volumes:
      - ./db-migrations:/migrations
    environment:
      - POSTGRESQL_USERNAME=mlp
      - POSTGRESQL_PASSWORD=mlp
      - POSTGRESQL_DATABASE=mlp
    entrypoint: ["sh", "-c"]
    command:
      - |
        export CONNECTION_URL=postgres://$$POSTGRESQL_USERNAME:$$POSTGRESQL_PASSWORD@postgres:5432/$$POSTGRESQL_DATABASE?sslmode=disable
        echo "Waiting for database..."
        until `/migrate  -path=/migrations/ -database $$CONNECTION_URL up`; do
          sleep 0.5
        done
        echo "Done!"

  keto:
    depends_on:
      - keto-db
      - keto-db-migrations
    image: oryd/keto:v0.4.3-alpha.2
    ports:
      - 4466:4466
    environment:
      - DSN=postgres://keto:keto@keto-db:5432/keto?sslmode=disable
    command:
      - serve

  keto-db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=keto
      - POSTGRESQL_PASSWORD=keto
      - POSTGRESQL_DATABASE=keto

  keto-db-migrations:
    depends_on:
      - keto-db
    image: oryd/keto:v0.4.3-alpha.2
    environment:
      - DSN=postgres://keto:keto@keto-db:5432/keto?sslmode=disable
    command:
      - migrate
      - sql
      - -e

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.23.5
    ports:
      - 5555:8080
    volumes:
      - ./static:/app:ro
    environment:
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/swagger.yaml
