/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Label struct {
	Key   string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}
