/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type VaultSecretStorageConfig struct {
	URL                 string `json:"url"`
	Role                string `json:"role,omitempty"`
	MountPath           string `json:"mount_path"`
	PathPrefix          string `json:"path_prefix"`
	AuthMethod          string `json:"auth_method"`
	GcpAuthType         string `json:"gcp_auth_type,omitempty"`
	ServiceAccountEmail string `json:"service_account_email,omitempty"`
}
