/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type SecretStorage struct {
	ID        int32                `json:"id,omitempty"`
	Name      string               `json:"name"`
	Type_     string               `json:"type"`
	Scope     string               `json:"scope"`
	ProjectID int32                `json:"project_id,omitempty"`
	Config    *SecretStorageConfig `json:"config"`
	CreatedAt time.Time            `json:"created_at,omitempty"`
	UpdatedAt time.Time            `json:"updated_at,omitempty"`
}
