/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ApplicationConfigNavigation struct {
	Label       string `json:"label,omitempty"`
	Destination string `json:"destination,omitempty"`
}
