/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ApplicationConfig struct {
	Api        string                        `json:"api,omitempty"`
	Icon       string                        `json:"icon,omitempty"`
	Navigation []ApplicationConfigNavigation `json:"navigation,omitempty"`
}
