/*
 * MLP API
 *
 * API Guide for accessing MLP API
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Application struct {
	Name        string             `json:"name"`
	Description string             `json:"description,omitempty"`
	Homepage    string             `json:"homepage"`
	Config      *ApplicationConfig `json:"config,omitempty"`
}
