// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GcsService is an autogenerated mock type for the GcsService type
type GcsService struct {
	mock.Mock
}

// DeleteArtifact provides a mock function with given fields: url
func (_m *GcsService) DeleteArtifact(url string) error {
	ret := _m.Called(url)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGcsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewGcsService creates a new instance of GcsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGcsService(t mockConstructorTestingTNewGcsService) *GcsService {
	mock := &GcsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
