// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"
	mock "github.com/stretchr/testify/mock"
)

// authHelper is an autogenerated mock type for the authHelper type
type authHelper struct {
	mock.Mock
}

// login provides a mock function with given fields: client
func (_m *authHelper) login(client *api.Client) (*api.Secret, error) {
	ret := _m.Called(client)

	var r0 *api.Secret
	if rf, ok := ret.Get(0).(func(*api.Client) *api.Secret); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewAuthHelper interface {
	mock.TestingT
	Cleanup(func())
}

// newAuthHelper creates a new instance of authHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newAuthHelper(t mockConstructorTestingTnewAuthHelper) *authHelper {
	mock := &authHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
