apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-encryption-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mlp.name" . }}
    chart: {{ include "mlp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mlp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  encryption-key: {{ .Values.mlp.encryption.key }}
