{{- if .Values.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gitlab
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  clientId: {{ .Values.gitlab.clientId | b64enc }}
  clientSecret: {{ .Values.gitlab.clientSecret | b64enc }}
{{- end }}
