apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlp.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mlp.name" .}}
    chart: {{ template "mlp.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mlp.service.externalPort }}
      targetPort: {{ .Values.mlp.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "mlp.name" .}}
    release: {{ .Release.Name }}
