// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/caraml-dev/mlp/api/models"
	mock "github.com/stretchr/testify/mock"
)

// SecretStorageService is an autogenerated mock type for the SecretStorageService type
type SecretStorageService struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *SecretStorageService) FindByID(id models.ID) (*models.SecretStorage, error) {
	ret := _m.Called(id)

	var r0 *models.SecretStorage
	if rf, ok := ret.Get(0).(func(models.ID) *models.SecretStorage); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SecretStorage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields:
func (_m *SecretStorageService) ListAll() ([]*models.SecretStorage, error) {
	ret := _m.Called()

	var r0 []*models.SecretStorage
	if rf, ok := ret.Get(0).(func() []*models.SecretStorage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SecretStorage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSecretStorageService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecretStorageService creates a new instance of SecretStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretStorageService(t mockConstructorTestingTNewSecretStorageService) *SecretStorageService {
	mock := &SecretStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
